site_name: cluster09
site_url: https://cluster09.podzone.cloud/cluster09/

site_description: Podzone Private Consumer cloud
site_author: Martin Colley

plugins:
    - search
    - mermaid2
    - swagger-ui-tag

theme:
  name: material
  analytics:
    gtag: G-SY1HLECK2G

nav:
    - README.md
    - Cilium.md
    - ClusterAPI.md
    - ClusterChart.md
    - ClusterTemplate.md
    - Flux.md
    - Harbor.md
    - Manifests.md
    - Network.md
    - Bastion.md
    - BastionDiagram.md
    - Storage.md
    - Talos.md
    - TalosTemplateCreation.md
    - Planning.md
    - References.md

