apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - observability.yaml
  - proxmox-secret.yaml
configMapGenerator:
  - name: observability-values
    files:
      - values.yaml=./observability-values.yaml
configurations:
  - kustomizeconfig.yaml