# Cluster API managed cluster manifests for Cluster 08

cluster:
  name: "cluster08"
network:
  ip_ranges: [192.168.4.181-192.168.4.187]
controlplane:
  endpoint_ip: 192.168.4.180
  machine_count: 1
  extra_manifests:
    - https://motttt.github.io/cluster09/cluster-manifests/gateway-api.yaml
    - https://motttt.github.io/cluster09/cluster-manifests/cilium.yaml
    - https://motttt.github.io/cluster09/cluster-manifests/flux.yaml
    - https://motttt.github.io/cluster09/cluster-manifests/flux-instance-cluster08.yaml
worker:
  machine_count: 1
