apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster08
resources:
  - cluster.yaml
  - cluster08-proxmox-secret.yaml
configMapGenerator:
  - name: cluster-values
    files:
      - values.yaml=./cluster-values.yaml
configurations:
  - kustomizeconfig.yaml