---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.cluster.name }}-workers
  namespace: {{ .Values.cluster.name }}
  labels:
    {{- include "cluster-chart.labels" . | nindent 4 }}
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.worker.machine_count }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: talosconfig-worker
          namespace: {{ .Values.cluster.name }}
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: {{ .Values.cluster.name }}-worker
        namespace: {{ .Values.cluster.name }}
      version: {{ .Values.cluster.kubernetes_version }}
