apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fluent-bit.yaml
configMapGenerator:
  - name: fluentbit-values
    namespace: flux-system
    files:
      - values.yaml=fluentbit-values.yaml
configurations:
  - kustomizeconfig.yaml
